language: node_js
node_js:
  - 12
  - 10
branches:
  only:
    - master
script:
  - git config --global user.name "${GH_NAME}"
  - git config --global user.email "${GH_EMAIL}"
  - echo "machine github.com login ${GH_NAME} password ${GH_TOKEN}" > ~/.netrc
  - npm install
  - npm run pretest
  - export GIT_USER="${GH_NAME}"
  - cd site && npm install && npm run deploy
